### ISSUE TITLE
Unable to Fetch Data

### ISSUE THREAD

**Issue by ketanmujumdar** [Fgerthoffert/jira-agile-velocity#46]
Hello, 

Thanks for an awesome application which can work on velocity. however, I am not able to get the data. Can you let me know how to work with google auth on Jira? 

```jav-cli_1  | Fetching data for day: 2019-09-01 to file: /root/jav-data/cache/completed-avengers-2019-09-01.ndjson... !
jav-cli_1  | Error: Request failed with status code 401
jav-cli_1  |     at createError (/usr/local/lib/node_modules/jira-agile-velocity/node_modules/axios/lib/core/createError.js:16:15)
jav-cli_1  |     at settle (/usr/local/lib/node_modules/jira-agile-velocity/node_modules/axios/lib/core/settle.js:17:12)
jav-cli_1  |     at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/jira-agile-velocity/node_modules/axios/lib/adapters/http.js:237:11)```

**Comment by Fgerthoffert** [comment]
Good question, I haven't tried it yet. 

Are you using a Jira Cloud instance?

**Comment by ketanmujumdar** [comment]
Hey @Fgerthoffert, Yes i am using jira cloud with google sign in.

**Comment by Fgerthoffert** [comment]
Sorry for the delay in responding @ketanmujumdar, I haven't tested it with jira cloud, but if I understand both this cloud and the latest jira version now have API tokens. I hope to be able to implement this in the next week or so.

**Comment by Fgerthoffert** [comment]
Sorry, this will not be implemented. You can look at github.com/zencrepes/ instead
